version: "3.8"

services:
  web:
    image: harveyimama/mintweb:v1
    ports:
      - "80:80"
    networks:
      - harvey
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    networks:
      - harvey    
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
  kafka:
    image: 'bitnami/kafka:latest'
    networks:
      - harvey
    links:
      - zookeeper:zk
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_MESSAGE_MAX_BYTES: 2000000
      KAFKA_CREATE_TOPICS: "Topic1:1:1"
      ALLOW_PLAINTEXT_LISTENER: 'yes'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  app2:
    image: harveyimama/mintapp2:v1
    ports:
      - "8081:8081"
    networks:
      - harvey
    depends_on:
      - kafka
    links:
      - kafka:kafka
  docker-mysql:
    image: mysql/mysql-server:latest
    restart: always
    networks:
      - harvey
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1W2w1s500.
      - MYSQL_DATABASE=mint
      - MYSQL_ROOT_HOST=%
  app1:
    image: harveyimama/mintapp1:v1
    ports:
      - "8080:8080"
    depends_on:
      - docker-mysql
      - kafka
    restart: always
    networks:
      - harvey
    links:
      - kafka:kafka
    environment:
      - SPRING_DATASOURCE_DRIVERCLASSNAME=com.mysql.cj.jdbc.Driver
networks:
  harvey:
